---
# tasks file for hosts_monitoring

- name: Wait for 60 min until the node {{ host_name }} reboots
  uri:
    url: "{{ URL_ASSISTED_INSTALLER_CLUSTER }}/hosts/{{ host_id }}"
    method: GET
    status_code: [200, 201]
    return_content: True
  register: host
  until: (host.json.progress.current_stage|default('') == 'Rebooting' and host.json.status == 'installing-pending-user-action')
         or
         host.json.progress.current_stage|default('') in ['Configuring', 'Done']
  retries: 60
  delay: 60

- name: Force rebooting on disk
  include_role:
    name: boot_disk
  vars:
    hosts: "{{ host.json.requested_hostname }}"
  when: host.json.progress.current_stage|default('') == 'Rebooting' and host.json.status == 'installing-pending-user-action'
