---
# tasks file for hosts_monitoring
- name: Wait for 60 min until the node {{ host_name }} reboots
  sonofspike.ocm.rest_api_call:
    url: "{{ URL_ASSISTED_INSTALLER_CLUSTER }}/hosts/{{ host_id }}"
    method: "GET"
    query: None
    data: {}
    access_token: "{{ access_token }}"
    api_token: "{{ api_token }}"
  register: response
  until: (response.json.progress.current_stage == 'Rebooting' and response.json.status == 'installing-pending-user-action')
         or
         response.json.progress.current_stage in ['Configuring', 'Done']
  retries: 60
  delay: 60

- name: Force rebooting on disk
  include_role:
    name: boot_disk
  vars:
    hosts: "{{ host.json.requested_hostname }}"
  when: host.json.progress.current_stage == 'Rebooting' and host.json.status == 'installing-pending-user-action'