---
# - name: Creating,Hosting the Assisted Installer Discovery ISO
#   hosts: assisted_installer
#   roles:
#   - okd.assisted_installer.validations
#   - okd.assisted_installer.setup_repository
#   - okd.assisted_installer.create_iso
#   - okd.assisted_installer.host_iso

- name: Mounting, Booting the Assisted Installer Discovery ISO
  hosts: masters, workers
  gather_facts: True
  strategy: free
  roles:
    - boot_iso
  vars:
    - debug: True
    - boot_iso_url: "{{ discovery_iso_server }}/{{ discovery_iso_name }}"
