---
- name: deploy_cluster.yml
  hosts: bastion
  gather_facts: True
  tasks:
  - name: get token (role)
    include_role:
        name: sonofspike.ocm.get_token
  - debug:
      var: response.result
  - name: Create cluster and generate Assisted Installer Discovery ISO
    block:
      - include_role:
          name: create_cluster
      - include_role:
          name: generate_discovery_iso 
    vars:
    - secure: False
    - create: True
    - generate: True
    - download: True
    - disconnected: "{{ use_mirror }}"
    - manifests: True
    - CLUSTER_NAME: "{{ cluster_name }}"
    - CLUSTER_ID: "{{ cluster_id }}"
    - BASE_DNS_DOMAIN: "{{ base_dns_domain }}"
    - ASSISTED_INSTALLER_HOST: "{{ hostvars['assisted_installer']['host'] }}"
    - ASSISTED_INSTALLER_PORT: "{{ hostvars['assisted_installer']['port'] }}"
    - SSH_PUBLIC_KEY: "{{ ssh_public_key }}"
    - PULL_SECRET: "{{ pull_secret }}"
    - CLUSTER_NETWORK_CIDR: "{{ cluster_network_cidr }}"
    - CLUSTER_NETWORK_HOST_PREFIX: "{{ cluster_network_host_prefix }}"
    - SERVICE_NETWORK_CIDR: "{{ service_network_cidr }}"
    - OPENSHIFT_VERSION: "{{ openshift_version }}"
    - VIP_DHCP_ALLOCATION: "{{ vip_dhcp_allocation }}"
    - INGRESS_VIP: "{{ ingress_vip }}"
    - API_VIP: "{{ api_vip }}"
    - FEATURE: "{{ feature }}"
    - MACHINE_NETWORK_CIDR: "{{ machine_network_cidr }}"
    - DOWNLOAD_DEST_FILE: "{{ discovery_iso_name }}"
    - DOWNLOAD_DEST_PATH: "/opt/http_store/data"
    - NTP_SERVER: "{{ ntp_server }}"
    rescue:
      - import_role:
          name: sonofspike.ocm.cleanup_cluster

- name: Mounting, Booting the Assisted Installer Discovery ISO
  hosts: masters, workers
  gather_facts: False
  strategy: free
  roles:
    - boot_iso
  vars:
    - debug: False
    - boot_iso_url: "{{ discovery_iso_server }}/{{ discovery_iso_name }}"

- name: Installing the cluster
  hosts: bastion
  gather_facts: True
  roles:
    - sonofspike.ocm.get_token
    - install_cluster
  vars:
    - access_token: "{{ access_token }}"
    - install: True
    - debug: False
    - ASSISTED_INSTALLER_HOST: "{{ hostvars['assisted_installer']['host'] }}"
    - ASSISTED_INSTALLER_PORT: "{{ hostvars['assisted_installer']['port'] }}"
    - CLUSTER_ID: "{{ cluster_id }}"
    - INGRESS_VIP: "{{ ingress_vip }}"
    - API_VIP: "{{ api_vip }}"
    - VIP_DHCP_ALLOCATION: "{{ vip_dhcp_allocation }}"

- name: Monitoring hosts installation
  hosts: masters, workers
  gather_facts: True
  strategy: free
  roles:
    - sonofspike.ocm.get_token
    - monitor_host
  vars:
    - debug: True
    - ASSISTED_INSTALLER_HOST: "{{ hostvars['assisted_installer']['host'] }}"
    - ASSISTED_INSTALLER_PORT: "{{ hostvars['assisted_installer']['port'] }}"
    - CLUSTER_ID: "{{ cluster_id }}"

# TODO: once completed grap cluster credentials
- name: Monitoring cluster installation
  hosts: bastion
  gather_facts: False
  roles:
    - sonofspike.ocm.get_token
    - monitor_cluster
  vars:
    - debug: True
    - ASSISTED_INSTALLER_HOST: "{{ hostvars['assisted_installer']['host'] }}"
    - ASSISTED_INSTALLER_PORT: "{{ hostvars['assisted_installer']['port'] }}"
    - CLUSTER_ID: "{{ cluster_id }}"
