---
# tasks file for manifests

- name: Load manifest
  set_fact:
    manifest: "{{ lookup('template', '{{ item }}.j2' )  | from_yaml | to_json(ensure_ascii=False) | string }}"
  when: manifests | bool == True

- debug:
    var: manifest
  when: debug and manifests  | bool == True

- name: apply manifest
  sonofspike.ocm.apply_manifest:
    manifest: "manifests"
    file_name: "{{ item }}"
    content: "{{ manifest | string | b64encode }}"
    url_apply_manifest: "{{ URL_ASSISTED_INSTALLER_CLUSTERS }}/{{ cluster_id }}/manifests"
    api_token: "{{ API_TOKEN}}"
    access_token: "{{ access_token }}"
  register: response
  
- debug:
    var: response
  when: debug and manifests  | bool == True